#Input file for Green's funciton-based reconstruciton algorithm

[inputs]
T_input_path = ./data/pulse_JSR_stackup_inputs.dat
downsample = 2
TC_depth = 0.00254

[params]
N = 12
N_x = 36
N_time = 10
NL_step_weight = 1
regularization_method = Tikhonov
lambda_reg_Tik = 5

[env]
P_nom = 0.1
T_rad_inf = 300

[stackup]
layers = [TPS,adhesive,substructure]
database = ./materials/

[TPS]
L = 0.03
material = TACOT

[adhesive]
L = 0.0014
material = HT424

[substructure]
L = 0.0127
material = Al_honeycomb